language: node_js

# Note: testing the scripts in a cross-compiler windows environment since
#       otherwise I couldn't test Win32CC.cmake.

before_install:
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -y update > /dev/null
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -y install cmake > /dev/null
#  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install mingw-w64 wine gcc-mingw32 gcc-mingw-w64 gfortran-mingw-w64 gcc-mingw-w64-x86-64 gcc-mingw-w64-i686  binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install mingw32 dpkg-cross wine gcc-mingw32 
  - mkdir -p ~/.cmake/
  - git clone git://github.com/daniperez/$MINGW_ARCH-boost.git ~/.cmake/mingw/
  - tar xvfj ~/.cmake/mingw/$MINGW_ARCH-boost-1.49.0.tar.bz2 -C ~/.cmake/mingw/ > /dev/null
env:
  - TOOLCHAIN_FILE=Windows-mingw-i686 MINGW_ARCH=i686-w64-mingw32
script:
  - "mkdir build -p"
  - "cd build"
  # Dunno why but I have to define BOOST_ROOT here and in the toolchain file.
  - "cmake -DBOOST_ROOT=~/.cmake/mingw/$MINGW_ARCH -DCMAKE_TOOLCHAIN_FILE=../win32cc/$TOOLCHAIN_FILE.cmake ../" 
  - "cmake -DCMAKE_TOOLCHAIN_FILE=../win32cc/$TOOLCHAIN_FILE.cmake ../" 
  - "make check"

notifications:
  email: true 
  on_failure: change
